version: 1

jobs:
  test_app:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/project
    steps:
      - checkout:
      - run:
          name: Running tests 
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            py.test -vv tests

  

workflows:
  version: 1
  test-all:
    jobs:
      - test_app

